### ISSUE TITLE
CI-BUG-Failures en build por tests de la épica con identificador 4

### ISSUE THREAD

**Issue by marmarsol4** [TerryIsmael/decide-part-pacodelucia#106]
No se hace la build dado que 2 tests de la épica indicada dan FAILURE.

Configuración utilizada: No es relevante en este caso, pues se ha detectado desde GitHub. 
Lugares del fallo:
- testExist (voting.tests.VotingByPreferenceModelTestCase)
- test_to_string (voting.tests.VotingByPreferenceTestCase)

Pasos para reproducirlo: No aplica, se ve en el commit en el action aplicado al commit https://github.com/TerryIsmael/decide-part-pacodelucia/commit/1cf5ae5f7f14c0f57937f68dee9ebb7ac18b0a6e

Prioridad de la incidencia: 3
Estado: Abierta
Rol: Tester

**Comment by juamornav3** [comment]
He comprobado el codacy y ya no hay problemas con la build
