### ISSUE TITLE
CI-BUG-Falla la build debido a un error en Setting up frontend test enviroment

### ISSUE THREAD

**Issue by olemornav** [TerryIsmael/decide-part-pacodelucia#109]
Descripción breve del fallo.
Configuración utilizada: github
Lugar del fallo o cambio (módulo): 

               - test de frontend .

Pasos para reproducir el fallo: 
                - Ejecutar el workflow de develop.
  
Prioridad de la incidencia: 4
Estado: Abierto 
Rol: Tester

**Comment by rafgoncas1** [comment]
He modificado el archivo de configuración de ejemplo del github actions, ahora ya se ha solucionado ese problema, pero sigue existiendo otro problema, he abierto una nueva issue.
