### ISSUE TITLE
CI-BUG-Posibilidad de que fallen los test de voting

### ISSUE THREAD

**Issue by rafgoncas1** [TerryIsmael/decide-part-pacodelucia#111]
Como se comenta en la issue #106, los test fallaban en varios sitios:

- testExist (voting.tests.VotingByPreferenceModelTestCase)
- test_to_string (voting.tests.VotingByPreferenceTestCase)

Tras investigar un poco sobre este fallo, me he percatado de que existe la posibilidad de que vuelva a fallar aún tras haber solventado estos errores en esos lugares por los siguientes motivos.

Django hace una llamada a la base de datos para obtener los datos pero no exige ningún orden, por tanto, al pedir varios objetos estos pueden llegar en distinto orden sin importar el orden de creación o ningún otro ordenamiento. Por como se ha diseñado el caso de prueba de testExist en la clase VotingModelTestCase esto podría llegar a ser un problema al igual que ha ocurrido anteriormente.

```
self.assertEquals(v.question.options.all()[0].option, "opcion 1")
```

Como se observa, por lo comentado, el primer objeto de la lista no tiene por que corresponderse siempre con la opción 1.
Recomiendo solucionar este posible fallo para evitar inconvenientes futuros.

### Configuración utilizada: 
No es relevante en este caso, pues se ha detectado tras un breve análisis de código en github tras lo sucedido en la anterior issue mencionada.

### Pasos para reproducirlo: 
No aplica, se ha derivado de [este commit](https://github.com/TerryIsmael/decide-part-pacodelucia/commit/1cf5ae5f7f14c0f57937f68dee9ebb7ac18b0a6e) tras realizar el workflow y que se refleje el fallo.

**Comment by juamornav3** [comment]
Arreglado
