### ISSUE TITLE
CI-DESPLIEGUE-Fallo con el frontend al desplegar en docker

### ISSUE THREAD

**Issue by juamornav3** [TerryIsmael/decide-part-pacodelucia#119]
Tras la realización del commit que añade funcionalidad de frontend, al loguearse con admin, sale un error en la ventana de login.

Configuración utilizada: No aplica

Pasos para reproducir:  Acceder a la ventana de login y entrar como admin.

Prioridad de la incidencia: 5

Estado: Finalizado

Rol: Dev-Ops

**Comment by rafgoncas1** [comment]
He creado una rama para modificar la configuración y añadir un dockerfile para desplegar el frontend de forma separada, y he configurado el archivo compose para que se comunique correctamente entre los demás contenedores.
