### ISSUE TITLE
CI-BUG-Error por un import al levantar el proyecto de frontend

### ISSUE THREAD

**Issue by JoseJavierAlcobendas** [TerryIsmael/decide-part-pacodelucia#134]
Tras haber unido la epica 5 y la 9 a la hora de ejecutar el comando: npm run dev en la carpeta del front, me sale el siguiente error:

Error: The following dependencies are imported but could not be resolved:
axios (imported by /home/egc2324/Escritorio/Proyecto/decide-part-pacodelucia/decide-frontend/src/components/Stats.vue?id=0)

Prioridad: 4
Estado: Abierto
Rol: Programador

**Comment by IsmaelRuizJurado** [comment]
El error se debe a que no tiene la librería axios instalada en su equipo.

Para ello, debe correr el comando "npm install axios" en su terminal.

Con esto se solucionará el problema.
