### ISSUE TITLE
CI-BUG-Error-con-selenium-driver-en-los-tests

### ISSUE THREAD

**Issue by PedroRuizAguilar** [TerryIsmael/decide-part-pacodelucia#139]
En la rama Grupo 2 y correr los tests del módulo visualizer se obtiene el siguiente error:

"File "decide-part-pacodelucia/decide/visualizer/tests.py", line 55, in test_simpleVisualizer
    response =self.driver.get(f'{self.live_server_url}/visualizer/{v.pk}/')
AttributeError: 'StatsViewTest' object has no attribute 'driver'"

Prioridad: 2
Estado: Revisión
Rol: Tester

**Comment by IsmaelRuizJurado** [comment]
Este error se debe a que le faltan por añadir las siguientes líneas de código en su test para que selenium le funcione bien:

"from selenium import webdriver
from selenium.webdriver.common.by import By"

En la función SetUp:
"self.base = BaseTestCase()
        self.base.setUp()
        options = webdriver.ChromeOptions()
        options.headless = True
        self.driver = webdriver.Chrome(options=options)"

y

"def tearDown(self):
        self.driver.quit()
        super().tearDown()"

Con esto sus test del módulo visualizer que user el driver de Selenium funcionarán correctamente.
