### ISSUE TITLE
CI-INTEGRATION-API Pull request de la epica 9 no pasa pruebas de calidad de codacy

### ISSUE THREAD

**Issue by PedroRuizAguilar** [TerryIsmael/decide-part-pacodelucia#148]
La pull request de la epica 9 a la rama develop no pasa las pruebas de calidad del codacy, debido a en la mayoria de casos imports no usados y variables no usadas

Prioridad: 2
Estado: Abierto
Rol: Programador

**Comment by IsmaelRuizJurado** [comment]
Ya se han realizado las correcciones pertinentes para solucionar los problemas de Codacy.
