### ISSUE TITLE
CI-INTEGRATION-package.json y package-lock.json innecesarios

### ISSUE THREAD

**Issue by rafgoncas1** [TerryIsmael/decide-part-pacodelucia#156]
Tras analizar brevemente los cambios integrados en develop, he notado que existen varios package.json y package-lock.json distribuidos a lo largo del proyecto. Estos archivos son únicamente necesarios en la carpeta frontend, por lo que deberían ser eliminados de todo lugar que no sea la carpeta decide-frontend.

#### ¿Dónde existen estos archivos?
- Carpeta base del proyecto (package-lock.json y package.json)
- Módulo booth (package-lock.json)

#### Además la carpeta node-modules que se encuentra en el directorio base debería ser eliminada.

Recomiendo revisar algún otro lugar donde existan estos archivos y verificar finalmente que no ha habido ningún problema con su eliminación.

No es necesario añadir configuración o pasos para reproducir ya que los test han pasado normalmente y no existen errores.

Prioridad: 2 (no es estrictamente necesario que se resuelva pero no es buena práctica y puede confundir a los demás)

**Comment by PedroRuizAguilar** [comment]
Archivos eliminados

**Comment by PedroRuizAguilar** [comment]
Pull request con la issue resuelta mergeada
