### ISSUE TITLE
CI-INTEGRATION-Añadir tests a workflow antes de hacer push a master

### ISSUE THREAD

**Issue by darkgigi** [TerryIsmael/decide-part-pacodelucia#157]
Tras realizar un análisis de los cambios realizados al workflow, sería conveniente que se lanzaran todos los test cada vez que se quiera hacer un merge a la rama master. 

<strong>¿Qué habría que hacer?</strong>
Modificar el workflow para que se lancen todos los test al hacer una pull request a master para mayor seguridad y comprobar que la versión es estable. Si alguno de estos test fallara no se podría hacer el merge a master.

No es necesario añadir configuración o pasos para reproducir ya que el workflow tiene una configuración propia.

Prioridad: 4 (debido a que se acerca el momento en el que tendremos que hacer merge a dicha rama)

**Comment by rafgoncas1** [comment]
He creado la pull request que añade este cambio al workflow. En cuanto se cierre se cerrará esta issue.
