### ISSUE TITLE
CI-INTEGRACIÓN- Arreglo del codacy para la implementacion de la Epic/10

### ISSUE THREAD

**Issue by Yuuta094** [TerryIsmael/decide-part-pacodelucia#183]
Arreglar los errors de codacy

ubicación: pull-request Epica/10

prioridad: 5

estado: abierto

rol: programador

**Comment by PedroRuizAguilar** [comment]
Debes irte a la revisión que te hace el codacy y mirar todos las issues medium y corregirlas asegurandote de que no dejar lo tipico de un import o variable no usada
