### ISSUE TITLE
CI-FEAT-TVAdminStatsFronted.py mal ubicado

### ISSUE THREAD

**Issue by Yuuta094** [TerryIsmael/decide-part-pacodelucia#186]
Añadir los test de TVAdminStatsFronted.py en la carpeta test correspondiente

luga: decide/voting

información adicional: si no esta en esa carpeta no se ejecutan los test

prioridad: 5

estado: abierta

rol: programador

**Comment by PedroRuizAguilar** [comment]
Deberia eliminar ese archivo "TVAdminStatsFronted.py" y colocar todos tus test en /voting/test_selenium.py

**Comment by anglorcas** [comment]
fixed
