### ISSUE TITLE
CI-BUG-Falla TestLoadVotingAdminStatsTestSuccess

### ISSUE THREAD

**Issue by marmarsol4** [TerryIsmael/decide-part-pacodelucia#203]
Se ha subido un test a la rama develop que falla y por tanto, no se hace la build correctamente. 

Configuración utilizada: No es relevante en este caso, es resultado del workflow. 
Lugar del fallo: decide.test_selenium.TestLoadVotingAdminStatsTestSuccess
Pasos para reproducirlo: No aplica.
Prioridad: 5

![image](https://github.com/TerryIsmael/decide-part-pacodelucia/assets/72874394/b8a6b15b-970e-48a7-9e63-d6538361451d)

Estado: Abierto
Rol: Tester

**Comment by rafgoncas1** [comment]
El test finalmente se ha eliminado.
