### ISSUE TITLE
CI-BUG-Excepción al intentar hacer el recuento de una votación

### ISSUE THREAD

**Issue by darkgigi** [TerryIsmael/decide-part-pacodelucia#206]
Al intentar probar la funcionalidad de las votaciones en frontend y backend he recibido una excepción. 

Configuración: he lanzado la versión de la rama develop, con el puerto 5173 para el frontend y el puerto 8000 para backend. El navegador utilizado ha sido Firefox.
La configuración del local_settings es: 
```
ALLOWED_HOSTS = ["*"]

CORS_ALLOWED_ORIGINS = ["http://localhost:5173"]
CSRF_ALLOWED_ORIGINS = ["http://localhost:5173"]
CORS_ALLOW_METHODS = ('DELETE', 'GET', 'OPTIONS', 'PATCH', 'POST', 'PUT')
CORS_ALLOW_HEADERS = ('authorization', 'content-type')
CORS_ALLOW_CREDENTIALS = True

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.common.CommonMiddleware',
]

# Modules in use, commented modules that you won't use
MODULES = [
    'authentication',
    'base',
    'booth',
    'census',
    'mixnet',
    'postproc',
    'store',
    'visualizer',
    'voting',
]

APIS = {
    'authentication': 'http://localhost:8000',
    'base': 'http://localhost:8000',
    'booth': 'http://localhost:8000',
    'census': 'http://localhost:8000',
    'mixnet': 'http://localhost:8000',
    'postproc': 'http://localhost:8000',
    'store': 'http://localhost:8000',
    'visualizer': 'http://localhost:8000',
    'voting': 'http://localhost:8000',
}

BASEURL = 'http://localhost:8000'
BACKEND_TEST_PORT = 8000
FRONTEND_TEST_PORT = 5173

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'decidedb',
        'USER': 'practicas',
        'PASSWORD': 'practicas',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# number of bits for the key, all auths should use the same number of bits
KEYBITS = 256
```
Lugar del fallo: Tally de las distintas votaciones

Pasos para reproducirlo:

1. Tener el servidor de backend abierto (el de frontend no es necesario)
2. Crear una votación nueva 
3. Hacer los pasos para que pase de start a tally

A continuación aporto capturas de las excepciones.
Excepción en una votación yes/no
![image](https://github.com/TerryIsmael/decide-part-pacodelucia/assets/113770002/0358048c-f94b-4a26-8857-6b2a83025570)
Excepción en una votación normal
![image](https://github.com/TerryIsmael/decide-part-pacodelucia/assets/113770002/b99d0e38-872f-4e12-8087-50e1a039ee4b)

Prioridad: 5
Estado: Abierto
Rol: Programador

**Comment by olemornav** [comment]
Se trata de un error de base de datos, te lo digo porque me ha pasado y al volver a crear la base de datos de nuevo funcionaba todo bien. No sé exactamente el por qué ocurre pero es un problema de la base de datos que no monta bien las tablas.
