### ISSUE TITLE
CI-INTERFACE-Pantalla de gráfica en inglés

### ISSUE THREAD

**Issue by olemornav** [TerryIsmael/decide-part-pacodelucia#212]
Las pantallas para ver gráficas con los resultados de votaciones están en inglés cuando deberían verse en español
Configuración utilizada: no es importante en este contexto.
Lugar del fallo:  decide-frontend/src/components/GraficaView.vue
Pasos para reproducirlo: visualizar la pantalla con las gráficas
Prioridad: 3
Estado: Abierto

**Comment by Yuuta094** [comment]
Hecho
