### ISSUE TITLE
CI-INTEGRATION-Nuevo filtro de censos no integrado en la vista de administrador

### ISSUE THREAD

**Issue by TerryIsmael** [TerryIsmael/decide-part-pacodelucia#220]
Se ha añadido una función de filtrado de usuarios compatibles de un censo, pero no está siendo utilizado en el frontend. Podría ser una buena idea implementarlo en la vista de censos

Configuración: no procede

Lugar del fallo: develop

Pasos para reproducirlo: no procede

Prioridad:1

Estado: Cerrado
Rol: Programador

**Comment by marmarsol4** [comment]
Se ha implementado el filtro funcional.
