### ISSUE TITLE
CI-INTEGRATION-Nuevo censo de votación por preferencia no asociado a su tipo de votación

### ISSUE THREAD

**Issue by olemornav** [TerryIsmael/decide-part-pacodelucia#222]
Se ha añadido un censo dedicado a las votaciones por preferencia en develop, pero no se ha cambiado la función que asocia el censo de las votaciones por preferencia al nuevo censo.

Configuración: No procede
Lugar del fallo: Módulos de store, booth, test de voting y voting
Pasos para reproducir: No procede

Prioridad: 3
Estado: Cerrado
Rol:Programador

**Comment by juamornav3** [comment]
Arreglado
