### ISSUE TITLE
CI-INTEGRATION-Despliegue en Docker se realiza en la rama develop

### ISSUE THREAD

**Issue by darkgigi** [TerryIsmael/decide-part-pacodelucia#236]
Actualmente se está creando el contenedor de Docker de la aplicación con los cambios de la rama develop. Esto debería cambiarse para que utilice la última versión de la rama master.

Configuración: No aplica
Lugar del fallo: /docker/Dockerfile
Pasos para repetir el problema: No aplica

Prioridad: 4
Estado: Abierta
Rol: DevOps

**Comment by rafgoncas1** [comment]
Ya he creado la pull request.
