### ISSUE TITLE
CI-INTEGRATION-Añadir funcionalidad de importación de censos a frontend

### ISSUE THREAD

**Issue by olemornav** [TerryIsmael/decide-part-pacodelucia#238]
La funcionalidad de censos ha sido añadida al backend pero no al frontend.
Configuración utilizada: no aplica para este error.
Lugar del fallo: decide-frontend/src/components/Census.vue
Pasos para reproducirlo: 
1. Levantar backend y frontend.
2. Visitar la pantalla y ver que falta un botón.
Prioridad: 2
Estado: Cerrado

**Comment by marmarsol4** [comment]
Realizado.
