### ISSUE TITLE
CI-INTEGRATION-Añadir a codacy que corra test cada vez que se haga push a una rama CI*

### ISSUE THREAD

**Issue by anglorcas** [TerryIsmael/decide-part-pacodelucia#244]
Actualmente hay que añadir todas las ramas manualmente para que se realizen los tests de codacy. 
La solucion es que se podria configurar de forma que reconozca toda rama que comienze con el prefijo CI como rama que tiene que correr test en evento de push.

Prioridad: 1
Estado: Abierta
Rol: DevOps

**Comment by TerryIsmael** [comment]
No es posible configurarlo para que se haga automáticamente. Se ha configurado para las épicas y las ramas importantes. Si alguna CI se considera importante o que ha hecho cambios muy significativos, se puede pedir al encargado de Codacy para que lo active para esa rama en concreto (@TerryIsmael).
