### ISSUE TITLE
CI-FEAT-Añadir boton de vista de admin/voting/stats

### ISSUE THREAD

**Issue by anglorcas** [TerryIsmael/decide-part-pacodelucia#245]
Actualmente no es posible acceder a la vista de admin/voting/stats.
La solucion que propongo es crear un boton en alguna parte de la interfaz del administrador.

Prioridad: 2
Estado: Cerrado
Rol: Programador

**Comment by marmarsol4** [comment]
Añadido como un nuevo apartado en el home de admin.
