### ISSUE TITLE
CI-INTEGRATION-Falta de algunas rutas en router.js

### ISSUE THREAD

**Issue by anglorcas** [TerryIsmael/decide-part-pacodelucia#248]
Por aplastamiento en la integracion faltan algunas rutas en el router.js.
La solucion es volver a añadir las rutas que fueran aplastadas

Prioridad: 3
Estado: Abierta
Rol: DevOps

**Comment by rafgoncas1** [comment]
En mi caso parece que todas mis rutas están correctas, podrías revisar qué rutas son las que se han eliminado?

**Comment by marmarsol4** [comment]
No faltan rutas en el router.js
