### ISSUE TITLE
CI-INTEGRATION-Falta de tests de Frontend

### ISSUE THREAD

**Issue by anglorcas** [TerryIsmael/decide-part-pacodelucia#249]
Actualmente aunque se han realizado una gran cantidad de vistas en frontend no hay practicamente ningun test, lo que conllevo a que ocurrieran problemas al subir cambios relacionados con las vistas de frontend sin que nadie se percatara.
La solucion es realizar algunos tests de Frontend mas.

Prioridad: 3
Estado: Abierta
Rol: DevOps

**Comment by TerryIsmael** [comment]
La explicación es un poco ambigua. Aunque no hay testing formal, se ha testeado profundamente de forma informal para no mergear a develop algo sin probar.  ¿Puedes especificar los errores para que intentemos solucionarlos?

**Comment by TerryIsmael** [comment]
Las pantallas de frontend han sido probadas exhaustivamente de forma manual, y no se han encontrado errores. Los tests automáticos de selenium quedan para futuras versiones si las hubiere.
