### ISSUE TITLE
CI-INTEGRATION-Corrección estética del botón de stats en Home.vue

### ISSUE THREAD

**Issue by IsmaelRuizJurado** [TerryIsmael/decide-part-pacodelucia#259]
En la vista Home, el botón para acceder a las estadísticas de una votación se sale de la tarjeta de las votaciones cerradas, lo que reduce la estética de la aplicación.

Como sugerencia para solucionarlo, se podría colocar este botón al lado del otro botón que contienen las votaciones.

Rol: Desarrollador
Prioridad: 4
Lugar de fallo: como tal no hay error, pero lo dicho se sitúa en Home.vue

**Comment by PedroRuizAguilar** [comment]
Los he puesto en un mismo style css y ya quedan bien
![image](https://github.com/TerryIsmael/decide-part-pacodelucia/assets/72878120/bac70842-8bd7-457d-a5eb-7a9929b5fca3)
