### ISSUE TITLE
CI-BUG-Fallo ver votaciones al borrar votacion

### ISSUE THREAD

**Issue by olemornav** [TerryIsmael/decide-part-pacodelucia#263]
Cuando se borra una votación de un usuario pero no el censo, el frontend no devuelve correctamente la request

Configuración: No aplica
Lugar del fallo: pantalla principal del frontend de decide
Pasos para reproducir: 
1 Crear una votación.
2 Crear un censo.
3 Borrar votación.
Prioridad: 3
Estado: Abierto
Rol: Programador

**Comment by darkgigi** [comment]
Arreglado, el fallo estaba en la función getVotingsByUser, que saltaba una excepción si intentaba buscar la votación asignada a un censo con una votación que no existiera o que ya se hubiera borrado anteriormente
