### ISSUE TITLE
CI-BUG-Error en las migraciones de census

### ISSUE THREAD

**Issue by juanrg8** [TerryIsmael/decide-part-pacodelucia#279]
Al intentar navegar por la página de admin de la aplicación, e intentar entrar en detalles de censos, se produce el error: ProgrammingError at /admincensus/census

Esto se debe a un fallo de desarrollo donde se ha borrado la migración inicial del censo y posteriormente se han añadido campos y creado una nueva migración inicial. Esto provoca el fallo en cualquier versión donde se haya migrado con la configuración anterior.

Configuración: No procede

Localización: migraciones de censo

Pasos para reproducir: Al iniciar la aplicación, y navegar por la página de admin, al intentar entrar en los detalles de censo aparece el error.

Prioridad: 3
Estado: Cerrado
Rol: programador

**Comment by TerryIsmael** [comment]
Prueba a borrar los archivos de migraciones y a hacer: 
```
manage.py makemigrations census
manage.py migrate census
```

**Comment by juanrg8** [comment]
Estupendo, ya funciona gracias!
