### ISSUE TITLE
CI-INTEGRATION-Añadir funcionalidad de censos para votaciones de preferencia a frontend

### ISSUE THREAD

**Issue by juanrg8** [TerryIsmael/decide-part-pacodelucia#281]
La funcionalidad de censos para votaciones de preferencia ha sido añadida al backend pero no al frontend.
Configuración utilizada: no aplica para este error.
Lugar del fallo: decide-frontend/src/components/Census.vue
Pasos para reproducirlo:

Levantar backend y frontend.
Visitar la pantalla y ver que falta un botón.
Prioridad: 2
Estado: Cerrado
Rol: devOps

**Comment by TerryIsmael** [comment]
Se podría implementar en futuras versiones de la aplicación, si las hubiere. Por temas de tiempo, solo podrá accederse desde backend.
