### ISSUE TITLE
CI-INTEGRATION-Añadir funcionalidad de reutilización de censos a frontend

### ISSUE THREAD

**Issue by juanrg8** [TerryIsmael/decide-part-pacodelucia#282]
La funcionalidad de reutilización de censos ha sido añadida al backend pero no al frontend.
Configuración utilizada: no aplica para este error.
Lugar del fallo: decide-frontend/src/components/Census.vue

Pasos para reproducirlo:
Levantar backend y frontend.
Visitar la pantalla y ver que falta la funcionalidad.
Prioridad: 2
Estado: Cerrado
Rol: devOps

**Comment by TerryIsmael** [comment]
Se podría implementar en futuras versiones de la aplicación, si las hubiere. Por temas de tiempo, solo podrá accederse desde backend.
