### ISSUE TITLE
CI-BUG-Error en gen_census.py

### ISSUE THREAD

**Issue by juanrg8** [TerryIsmael/decide-part-pacodelucia#283]
Al ejecutar gen_census.py aparece el error invalid usernames y no se realiza el registro de usuarios

Configuración: No procede

Localización: /loadtest/gen_census.py

Pasos para reproducir: Al ejecutar python gen_census.py

Prioridad: 3
Estado: Abierto
Rol: programador

**Comment by TerryIsmael** [comment]
El fallo está relacionado con los cambios en la función de registro, dado que ahora requiere un correo electrónico. Por temas de tiempo, no se realizará una corrección, pero si el proyecto vuelve a abrirse, se solucionará
