### ISSUE TITLE
CI-FEAT-Crear populador con datos de ejemplo para agilizar pruebas del sistema

### ISSUE THREAD

**Issue by juanrg8** [TerryIsmael/decide-part-pacodelucia#284]
Las pruebas de sistema pueden ser algo tediosas de realizar, para solucionarlo se propone la creación de un populador con datos de ejemplo para hacer este proceso más ágil y eficiente.

Prioridad: 1
Estado: Abierto
Rol: Programador

**Comment by TerryIsmael** [comment]
Se podría implementar en futuras versiones de la aplicación, si las hubiere. Por temas de tiempo, se planteará como una futura idea.
